### ISSUE TITLE
Migrate to depend on the new inspect objects library

### ISSUE THREAD

**Issue by aaronlippold** [mitre/inspec_tools#86]
https://github.com/inspec/inspec-objects

**Comment by aaronlippold** [comment]
@kevin-j-smith maybe we can merge this as part of your PR set. I think we should just get ahead of this before the next release of inspect makes stuff break :-)

**Comment by lukemalinowski** [comment]
I believe we still need inspec as we try to setup inspec_tools as a plugin for inspec.
```
NoMethodError: undefined method `plugin' for Inspec:Module
  /Users/lmalinowski/git/inspec_tools/lib/inspec_tools/plugin_cli.rb:25:in `<module:InspecToolsPlugin>'
  /Users/lmalinowski/git/inspec_tools/lib/inspec_tools/plugin_cli.rb:24:in `<module:InspecPlugins>'
  /Users/lmalinowski/git/inspec_tools/lib/inspec_tools/plugin_cli.rb:23:in `<top (required)>'
  /Users/lmalinowski/git/inspec_tools/lib/inspec_tools/cli.rb:9:in `require_relative'
  /Users/lmalinowski/git/inspec_tools/lib/inspec_tools/cli.rb:9:in `<top (required)>'
  inspec_tools:12:in `require'
  inspec_tools:12:in `<top (required)>'
```

**Comment by lukemalinowski** [comment]
If the plugin code is in inspec-core we would be okay. Since inspec-objects depends on inspec-core
